#导航栏
menu:
  Home: /
  Archive: /archives
  Page: /page

# 站点微缩图
favicon: /images/favicon.ico

# 头像
avator: https://cdn.jsdelivr.net/gh/wxc0914/image/a3625c26bc8735174100f6d487763b06.png
# 一言
hitokoto: 我们都是阴沟里的虫子，但总还是得有人仰望星空。

# 导航栏背景图片
backgroundUrl: https://cdn.jsdelivr.net/gh/wxc0914/image/342211649c34edaa0fef32c4eaa647c1.jpg
# 主题色
themeColor: tomato

# 博客托管仓库
repo: 仓库地址
# ICP备案号
icp: 备案号

# 评论 https://utteranc.es/
utterances:
  enable: true
  repo: [ENTER REPO HERE]
  theme: github-light
