#导航栏
menu:
  Home: /
  Archive: /archives
  Page: /page

# 站点微缩图
favicon: /images/favicon.ico

# 头像
avator: https://cdn.jsdelivr.net/gh/wxc0914/image/a3625c26bc8735174100f6d487763b06.png
# 一言
hitokoto: 我们都是阴沟里的虫子，但总还是得有人仰望星空。

# 导航栏背景图片
backgroundUrl: https://cdn.jsdelivr.net/gh/wxc0914/image/342211649c34edaa0fef32c4eaa647c1.jpg
# 主题色
themeColor: tomato

# 博客托管仓库
repo: 仓库地址
# ICP备案号
icp: 备案号

# 评论 https://giscus.app/zh-CN
giscus:
  enable: true
  repo:
  repo_id:
  category: Announcements
  category_id: DIC_kwDOFcPKls4CO_hE
  mapping: pathname
  reactions_enabled: 1
  emit_metadata: 0
  input_position: top
  theme: light
  lang: zh-CN
  loading: lazy
  crossorigin: anonymous
