#导航栏
menu:
  Home: /
  About: /about

# 站点微缩图
favicon: /images/cactus.png

# 头像
avator: https://cdn.jsdelivr.net/gh/wxc0914/image/a3625c26bc8735174100f6d487763b06.png

# ICP备案号
icp: 蜀ICP备2021014778号-1

# 主题色
site-icon: "/images/cactus.png"