#导航栏
menu:
  Home: /
  Archive: /archives
  About: /about
  Link: /link

# 站点微缩图
favicon: /images/cactus.png

# 头像
avator: https://cdn.jsdelivr.net/gh/wxc0914/image/a3625c26bc8735174100f6d487763b06.png
# 一言
hitokoto: 我们都是阴沟里的虫子，但总还是得有人仰望星空。

# 导航栏背景图片
backgroundUrl: https://cdnb.artstation.com/p/assets/images/images/025/423/333/medium/sylvain-sarrailh-yoshicollines.jpg?1585749317
# 主题色
themeColor: tomato

# 博客托管仓库
repo: 仓库地址
# ICP备案号
icp: 备案号

# 友链
link:
  - name: 博客名
    avator: https://cdn.jsdelivr.net/gh/wxc0914/image/a3625c26bc8735174100f6d487763b06.png
    site: 博客地址
    intro: 座右铭


# 评论 https://utteranc.es/
utterances:
  enable: true
  repo: [ENTER REPO HERE]
  theme: github-light
